var sourcesIndex = JSON.parse('{\
"adler":["",[],["algo.rs","lib.rs"]],\
"bit_field":["",[],["lib.rs"]],\
"bitflags":["",[],["lib.rs"]],\
"bytemuck":["",[],["allocation.rs","anybitpattern.rs","checked.rs","contiguous.rs","internal.rs","lib.rs","no_uninit.rs","offset_of.rs","pod.rs","pod_in_option.rs","transparent.rs","zeroable.rs","zeroable_in_option.rs"]],\
"byteorder":["",[],["io.rs","lib.rs"]],\
"cfg_if":["",[],["lib.rs"]],\
"color_quant":["",[],["lib.rs","math.rs"]],\
"complex_math":["",[],["lib.rs","test_complex.rs"]],\
"crc32fast":["",[["specialized",[],["mod.rs","pclmulqdq.rs"]]],["baseline.rs","combine.rs","lib.rs","table.rs"]],\
"crossbeam_deque":["",[],["deque.rs","lib.rs"]],\
"crossbeam_epoch":["",[["sync",[],["list.rs","mod.rs","once_lock.rs","queue.rs"]]],["atomic.rs","collector.rs","default.rs","deferred.rs","epoch.rs","guard.rs","internal.rs","lib.rs"]],\
"crossbeam_utils":["",[["atomic",[],["atomic_cell.rs","consume.rs","mod.rs","seq_lock.rs"]],["sync",[],["mod.rs","once_lock.rs","parker.rs","sharded_lock.rs","wait_group.rs"]]],["backoff.rs","cache_padded.rs","lib.rs","thread.rs"]],\
"either":["",[],["iterator.rs","lib.rs"]],\
"exr":["",[["block",[],["chunk.rs","lines.rs","mod.rs","reader.rs","samples.rs","writer.rs"]],["compression",[["b44",[],["mod.rs","table.rs"]],["piz",[],["huffman.rs","mod.rs","wavelet.rs"]]],["mod.rs","pxr24.rs","rle.rs","zip.rs"]],["image",[["read",[],["any_channels.rs","image.rs","layers.rs","levels.rs","mod.rs","samples.rs","specific_channels.rs"]],["write",[],["channels.rs","layers.rs","mod.rs","samples.rs"]]],["crop.rs","mod.rs","pixel_vec.rs","recursive.rs"]],["meta",[],["attribute.rs","header.rs","mod.rs"]]],["error.rs","io.rs","lib.rs","math.rs"]],\
"fdeflate":["",[],["compress.rs","decompress.rs","lib.rs","tables.rs"]],\
"flate2":["",[["deflate",[],["bufread.rs","mod.rs","read.rs","write.rs"]],["ffi",[],["mod.rs","rust.rs"]],["gz",[],["bufread.rs","mod.rs","read.rs","write.rs"]],["zlib",[],["bufread.rs","mod.rs","read.rs","write.rs"]]],["bufreader.rs","crc.rs","lib.rs","mem.rs","zio.rs"]],\
"flume":["",[],["lib.rs","signal.rs"]],\
"getrandom":["",[],["error.rs","error_impls.rs","lazy.rs","lib.rs","linux_android.rs","use_file.rs","util.rs","util_libc.rs"]],\
"gif":["",[["reader",[],["converter.rs","decoder.rs","mod.rs"]]],["common.rs","encoder.rs","lib.rs","traits.rs"]],\
"half":["",[["bfloat",[],["convert.rs"]],["binary16",[["arch",[],["x86.rs"]]],["arch.rs"]]],["bfloat.rs","binary16.rs","leading_zeros.rs","lib.rs","slice.rs","vec.rs"]],\
"image":["",[["codecs",[["bmp",[],["decoder.rs","encoder.rs","mod.rs"]],["hdr",[],["decoder.rs","encoder.rs","mod.rs"]],["ico",[],["decoder.rs","encoder.rs","mod.rs"]],["jpeg",[],["decoder.rs","encoder.rs","entropy.rs","mod.rs","transform.rs"]],["pnm",[],["autobreak.rs","decoder.rs","encoder.rs","header.rs","mod.rs"]],["tga",[],["decoder.rs","encoder.rs","header.rs","mod.rs"]],["webp",[],["decoder.rs","encoder.rs","extended.rs","huffman.rs","loop_filter.rs","lossless.rs","lossless_transform.rs","mod.rs","transform.rs","vp8.rs"]]],["dds.rs","dxt.rs","farbfeld.rs","gif.rs","openexr.rs","png.rs","qoi.rs","tiff.rs"]],["imageops",[],["affine.rs","colorops.rs","mod.rs","sample.rs"]],["io",[],["free_functions.rs","mod.rs","reader.rs"]],["math",[],["mod.rs","rect.rs","utils.rs"]],["utils",[],["mod.rs"]]],["animation.rs","buffer.rs","color.rs","dynimage.rs","error.rs","flat.rs","image.rs","lib.rs","traits.rs"]],\
"itoa":["",[],["lib.rs","udiv128.rs"]],\
"jpeg_decoder":["",[["arch",[],["mod.rs","neon.rs","ssse3.rs","wasm.rs"]],["decoder",[],["lossless.rs"]],["worker",[],["immediate.rs","mod.rs","multithreaded.rs","rayon.rs"]]],["decoder.rs","error.rs","huffman.rs","idct.rs","lib.rs","marker.rs","parser.rs","upsampler.rs"]],\
"lebe":["",[],["lib.rs"]],\
"libc":["",[["unix",[["linux_like",[["linux",[["arch",[["generic",[],["mod.rs"]]],["mod.rs"]],["gnu",[["b64",[["x86_64",[],["align.rs","mod.rs","not_x32.rs"]]],["mod.rs"]]],["align.rs","mod.rs"]]],["align.rs","mod.rs","non_exhaustive.rs"]]],["mod.rs"]]],["align.rs","mod.rs"]]],["fixed_width_ints.rs","lib.rs","macros.rs"]],\
"lock_api":["",[],["lib.rs","mutex.rs","remutex.rs","rwlock.rs"]],\
"miniz_oxide":["",[["deflate",[],["buffer.rs","core.rs","mod.rs","stream.rs"]],["inflate",[],["core.rs","mod.rs","output_buffer.rs","stream.rs"]]],["lib.rs","shared.rs"]],\
"num_traits":["",[["ops",[],["bytes.rs","checked.rs","euclid.rs","inv.rs","mod.rs","mul_add.rs","overflowing.rs","saturating.rs","wrapping.rs"]]],["bounds.rs","cast.rs","float.rs","identities.rs","int.rs","lib.rs","macros.rs","pow.rs","real.rs","sign.rs"]],\
"png":["",[["decoder",[["transform",[],["palette.rs"]]],["mod.rs","stream.rs","transform.rs","zlib.rs"]]],["adam7.rs","chunk.rs","common.rs","encoder.rs","filter.rs","lib.rs","srgb.rs","text_metadata.rs","traits.rs"]],\
"ppv_lite86":["",[["x86_64",[],["mod.rs","sse2.rs"]]],["lib.rs","soft.rs","types.rs"]],\
"proc_macro2":["",[],["detection.rs","extra.rs","fallback.rs","lib.rs","marker.rs","parse.rs","rcvec.rs","wrapper.rs"]],\
"qoi":["",[],["consts.rs","decode.rs","encode.rs","error.rs","header.rs","lib.rs","pixel.rs","types.rs","utils.rs"]],\
"quote":["",[],["ext.rs","format.rs","ident_fragment.rs","lib.rs","runtime.rs","spanned.rs","to_tokens.rs"]],\
"rand":["",[["distributions",[],["bernoulli.rs","distribution.rs","float.rs","integer.rs","mod.rs","other.rs","slice.rs","uniform.rs","utils.rs","weighted.rs","weighted_index.rs"]],["rngs",[["adapter",[],["mod.rs","read.rs","reseeding.rs"]]],["mock.rs","mod.rs","std.rs","thread.rs"]],["seq",[],["index.rs","mod.rs"]]],["lib.rs","prelude.rs","rng.rs"]],\
"rand_chacha":["",[],["chacha.rs","guts.rs","lib.rs"]],\
"rand_core":["",[],["block.rs","error.rs","impls.rs","le.rs","lib.rs","os.rs"]],\
"rayon":["",[["collections",[],["binary_heap.rs","btree_map.rs","btree_set.rs","hash_map.rs","hash_set.rs","linked_list.rs","mod.rs","vec_deque.rs"]],["compile_fail",[],["cannot_collect_filtermap_data.rs","cannot_zip_filtered_data.rs","cell_par_iter.rs","mod.rs","must_use.rs","no_send_par_iter.rs","rc_par_iter.rs"]],["iter",[["collect",[],["consumer.rs","mod.rs"]],["find_first_last",[],["mod.rs"]],["plumbing",[],["mod.rs"]]],["chain.rs","chunks.rs","cloned.rs","copied.rs","empty.rs","enumerate.rs","extend.rs","filter.rs","filter_map.rs","find.rs","flat_map.rs","flat_map_iter.rs","flatten.rs","flatten_iter.rs","fold.rs","fold_chunks.rs","fold_chunks_with.rs","for_each.rs","from_par_iter.rs","inspect.rs","interleave.rs","interleave_shortest.rs","intersperse.rs","len.rs","map.rs","map_with.rs","mod.rs","multizip.rs","noop.rs","once.rs","panic_fuse.rs","par_bridge.rs","positions.rs","product.rs","reduce.rs","repeat.rs","rev.rs","skip.rs","skip_any.rs","skip_any_while.rs","splitter.rs","step_by.rs","sum.rs","take.rs","take_any.rs","take_any_while.rs","try_fold.rs","try_reduce.rs","try_reduce_with.rs","unzip.rs","update.rs","while_some.rs","zip.rs","zip_eq.rs"]],["slice",[],["chunks.rs","mergesort.rs","mod.rs","quicksort.rs","rchunks.rs"]]],["array.rs","delegate.rs","lib.rs","math.rs","option.rs","par_either.rs","prelude.rs","private.rs","range.rs","range_inclusive.rs","result.rs","split_producer.rs","str.rs","string.rs","vec.rs"]],\
"rayon_core":["",[["broadcast",[],["mod.rs"]],["compile_fail",[],["mod.rs","quicksort_race1.rs","quicksort_race2.rs","quicksort_race3.rs","rc_return.rs","rc_upvar.rs","scope_join_bad.rs"]],["join",[],["mod.rs"]],["scope",[],["mod.rs"]],["sleep",[],["counters.rs","mod.rs"]],["spawn",[],["mod.rs"]],["thread_pool",[],["mod.rs"]]],["job.rs","latch.rs","lib.rs","private.rs","registry.rs","unwind.rs"]],\
"ryu":["",[["buffer",[],["mod.rs"]],["pretty",[],["exponent.rs","mantissa.rs","mod.rs"]]],["common.rs","d2s.rs","d2s_full_table.rs","d2s_intrinsics.rs","digit_table.rs","f2s.rs","f2s_intrinsics.rs","lib.rs"]],\
"scopeguard":["",[],["lib.rs"]],\
"serde":["",[["de",[],["format.rs","ignored_any.rs","impls.rs","mod.rs","seed.rs","size_hint.rs","value.rs"]],["private",[],["de.rs","doc.rs","mod.rs","ser.rs"]],["ser",[],["fmt.rs","impls.rs","impossible.rs","mod.rs"]]],["integer128.rs","lib.rs","macros.rs"]],\
"serde_derive":["",[["internals",[],["ast.rs","attr.rs","case.rs","check.rs","ctxt.rs","mod.rs","receiver.rs","respan.rs","symbol.rs"]]],["bound.rs","de.rs","dummy.rs","fragment.rs","lib.rs","pretend.rs","ser.rs","this.rs"]],\
"serde_json":["",[["features_check",[],["mod.rs"]],["io",[],["mod.rs"]],["value",[],["de.rs","from.rs","index.rs","mod.rs","partial_eq.rs","ser.rs"]]],["de.rs","error.rs","iter.rs","lib.rs","macros.rs","map.rs","number.rs","read.rs","ser.rs"]],\
"server":["",[["server_services",[],["mod.rs","server.rs"]]],["main.rs"]],\
"shared_lib":["",[["complementary_types",[],["mod.rs","pixeldata.rs","pixelintensity.rs","point.rs","range.rs","resolution.rs","u8data.rs"]],["fractal_implementation",[],["fractal.rs","fractal_calcul.rs","mod.rs"]],["fractal_types",[],["iterated_sin_z.rs","julia_descriptor.rs","mandelbrot.rs","mod.rs","newton_raphson_z_3.rs","newton_raphson_z_4.rs","nova_newton_raphson_z_3.rs","nova_newton_raphson_z_4.rs"]],["messages",[],["fragment_method_json.rs","message.rs","mod.rs"]],["messages_methods",[],["messages_methods.rs","mod.rs"]]],["lib.rs"]],\
"simd_adler32":["",[["imp",[],["avx2.rs","avx512.rs","mod.rs","scalar.rs","sse2.rs","ssse3.rs","wasm.rs"]]],["hash.rs","lib.rs"]],\
"smallvec":["",[],["lib.rs"]],\
"spin":["",[["mutex",[],["spin.rs"]]],["barrier.rs","lazy.rs","lib.rs","mutex.rs","once.rs","relax.rs","rwlock.rs"]],\
"syn":["",[["gen",[],["clone.rs"]]],["attr.rs","bigint.rs","buffer.rs","custom_keyword.rs","custom_punctuation.rs","data.rs","derive.rs","discouraged.rs","drops.rs","error.rs","export.rs","expr.rs","ext.rs","gen_helper.rs","generics.rs","group.rs","ident.rs","lib.rs","lifetime.rs","lit.rs","lookahead.rs","mac.rs","macros.rs","meta.rs","op.rs","parse.rs","parse_macro_input.rs","parse_quote.rs","path.rs","print.rs","punctuated.rs","restriction.rs","sealed.rs","span.rs","spanned.rs","thread.rs","token.rs","ty.rs","verbatim.rs"]],\
"tiff":["",[["decoder",[],["ifd.rs","image.rs","mod.rs","stream.rs","tag_reader.rs"]],["encoder",[["compression",[],["deflate.rs","lzw.rs","mod.rs","packbits.rs","uncompressed.rs"]]],["colortype.rs","mod.rs","tiff_value.rs","writer.rs"]]],["bytecast.rs","error.rs","lib.rs","tags.rs"]],\
"unicode_ident":["",[],["lib.rs","tables.rs"]],\
"weezl":["",[],["decode.rs","encode.rs","error.rs","lib.rs"]],\
"worker":["",[["client_services",[],["mod.rs","worker.rs"]]],["main.rs"]],\
"zune_inflate":["",[["encoder",[],["fast_match_finder.rs"]]],["bitstream.rs","constants.rs","decoder.rs","encoder.rs","errors.rs","lib.rs","utils.rs"]]\
}');
createSourceSidebar();
